### ISSUE TITLE
M1 support?

### ISSUE THREAD

**Issue by fdncred** [saethlin/fls#13]
Any chance on getting this to compile on Apple's M1 architecture?

**Comment by saethlin** [comment]
Theoretically I do not have any objections to this. If you or someone else wants to submit patches to this repo and `veneer`: https://github.com/saethlin/veneer I would be happy to review them.

**Comment by saethlin** [comment]
This project should compile for aarch64, and should work on Asahi Linux. If it doesn't, please open another issue.
