### ISSUE TITLE
Feature Request: macOS

### ISSUE THREAD

**Issue by ijoseph** [saethlin/fls#15]
Expected: implemented for macOS

Actual: dos not:

```bash
❯ cargo install fls
    Updating crates.io index
  Downloaded fls v0.1.0
  Downloaded 1 crate (18.6 KB) in 0.37s
  Installing fls v0.1.0
  Downloaded compiler_builtins v0.1.90
  Downloaded veneer-macros v0.1.0
  Downloaded veneer v0.1.1
  Downloaded sc v0.2.7
  Downloaded 4 crates (231.8 KB) in 0.30s
   Compiling compiler_builtins v0.1.90
   Compiling libc v0.2.140
   Compiling sc v0.2.7
   Compiling tinyvec_macros v0.1.1
   Compiling bitflags v1.3.2
   Compiling fls v0.1.0
   Compiling veneer-macros v0.1.0
   Compiling unicode-width v0.1.10
   Compiling tinyvec v1.6.0
   Compiling veneer v0.1.1
error: This library is only implemented for linux
```

Environment: 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/549191/228055434-a65ed355-c7be-4722-831b-b8f57f83fa5a.png">

**Comment by saethlin** [comment]
> Expected: implemented for macOS

`fls`'s whole game is not going through the POSIX interfaces and making syscalls directly. I am not interesting in maintaining this project across kernel ABI breaks. If you or someone else is interesting in contributing and maintaining support for the other POSIX-y platforms I'm willing to review patches.

I will try to clarify this all in the compile error.

**Comment by ijoseph** [comment]
Makes sense — very helpful reply. I learned something —  I didn't realize that syscalls were sufficiently different between macOS and Linux to be an impediment for something like this.  I'm now going to look down that rabbit hole a bit!
